# Generated by Django 5.2.3 on 2025-07-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('DANSE', 'Danse'), ('SPORT', 'Sport'), ('CHANT', 'Chant'), ('DESSIN', 'Dessin'), ('SLAM', 'Slam')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeCandidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ouvert', 'ouvert'), ('ferme', 'ferme')], default='ouvert', max_length=50)),
                ('allowed_voter_criteria', models.JSONField(default=dict)),
                ('listeCandidats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electionapp.listecandidats')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_set', to='electionapp.election')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='resultat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_election', to='electionapp.resultat'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('matricule', models.CharField(max_length=4, unique=True)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('is_first_login', models.BooleanField(default=True)),
                ('fingerprint_id', models.CharField(blank=True, max_length=10, null=True)),
                ('classe', models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1'), (5, 'M2')], default=1)),
                ('mention', models.CharField(choices=[('INFO', 'Informatique'), ('SA', 'Sciences Agronomiques'), ('ECO', 'Économie et Commerce'), ('LEA', 'Langues Étrangères Appliquées'), ('ST', 'Sciences de la Terre'), ('DROIT', 'Droit')], default='INFO', max_length=10)),
                ('sport_type', models.CharField(blank=True, choices=[('FOOT', 'Football'), ('BASKET', 'Basketball'), ('VOLLEY', 'Volleyball'), ('PET', 'Pétanque')], max_length=10, null=True)),
                ('activites', models.ManyToManyField(blank=True, to='electionapp.activite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listecandidats',
            name='candidats',
            field=models.ManyToManyField(to='electionapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estNul', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='electionapp.utilisateur')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='electionapp.utilisateur')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='electionapp.election')),
            ],
        ),
        migrations.AddField(
            model_name='resultat',
            name='listeVote',
            field=models.ManyToManyField(to='electionapp.vote'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['startdate', 'enddate'], name='electionapp_startda_a1f50f_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['statut'], name='electionapp_statut_156ffe_idx'),
        ),
    ]
